# Generated by Django 3.1.2 on 2021-06-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Destination',
        ),
    ]
